### PR TITLE
Added `Project` class to handle repository interactions

### PR DESCRIPTION
**Pull request by ChrisTimperley**
Addresses issues #7 and #16.

### CODE REVIEW

**Comment by ChrisTimperley** [comment]
I'm a bit perplexed; the code builds and passes the test suite on my local machine.

**Comment by ChrisTimperley** [comment]
I'm not entirely happy with these changes. Having to unbox `Project.repo` every time you want to interact with a method in `util` is ugly. I have two alternative suggestions:

1. we modify the methods in `util`  to operate on projects rather than repos. Each method would be responsible for unboxing the project, rather than the caller.
2. we move the various methods in `util` to become methods of `Project`. This seems the most sensible to me.

What do you think @jlacomis @mausotog?

**Comment by jlacomis** [comment]
@ChrisTimperley Your tests were failing to catch the problem because your `.repo` directory already existed.

**Comment by jlacomis** [comment]
@ChrisTimperley I vote for moving the `util` methods over to the `Project` object. All of these sure _sound_ like properties of projects.

**Comment by ChrisTimperley** [comment]
@jlacomis Ah, nice spot!

**Pull request merged**
