### PR TITLE
Added simple benchmark that exposes poor performance

### PR DESCRIPTION
**Pull request by ChrisTimperley**
Should help to solve #29 and #30

### CODE REVIEW

**Comment by jlacomis** [comment]
I'm getting some very strange output to profile.txt when running the command in the README:
```
[10:43] gs17931:benchmarks :) > head profile.txt 
�)�~��(<built-in method sys.getdefaultencoding>)�rgg{��D/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/compat.py�<module>)rrgg0)rr�<built-in method sys._getframe>)�r
g�'eRC�>g�'eRC�>{��*/usr/lib/python3.6/collections/__init__.pyie�
namedtuple)r
r
g�'eRC�>g�'eRC�>0)rr�<built-in method gc.collect>)�rg$�j���?g$�j���?{��G/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/repo/base.py���close)rrg$�j���?g$�j���?0)rr�&<method 'find' of 'bytearray' objects>)i4i4g�'eRC?g�'eRC?{��!/usr/lib/python3.6/sre_compile.py���_optimize_charset)i4i4g�'eRC?g�'eRC?0)rr�+<method 'translate' of 'bytearray' objects>)�rg?�̔���>g?�̔���>{�rix�
_mk_bitmap)rrg?�̔���>g?�̔���>0)rr�$<method 'decode' of 'bytes' objects>)i��i��g�kzPP��?g�kzPP��?{)�D/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/remote.pyi��
<listcomp>)�r g���%�>g���%�>��J/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/objects/base.py�f�hexsha)i�"i�"g��'�H0u?g��'�H0u?�r�C�
                                                    safe_decode)iq	iq	g�h8en��?g�h8en��?r)rrg�������>g�������>��D/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/config.pyi�_read)�$r+gT�qs*�>gT�qs*�>��L/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/objects/commit.pyi��
         _deserialize)��r/g,C��6?g,C��6?��A/usr0/home/jlacomis/.local/lib/python3.6/site-packages/git/cmd.pyi
�
  _prepare_ref)i��i��g{Cr2q�?g{Cr2q�?)�/usr/lib/python3.6/os.pyi��decode)i��i��g�r�m�B�?gtg3Lm����?g3Lm����?{�r1iM�execute)ititgGXT��${?gGXT��${?��/usr/lib/python3.6/posixpath.py�I�join)i�di�dg C�*�?g C�*�?0)rr�"<method 'join' of 'bytes' objects>)ititg�
                                                                           S[� �?g�
                                                                                   S[� �?{�� /usr/lib/python3.6/subprocess.pyi��
                            _communicate)ititg�
                                                S[� �?g�
                                                        S[� �?0)rr�$<method 'lstrip' of 'bytes' objects>)�BrCg
�F��>g
�F��>{�ri��blame_incremental)rCrCg
[10:43] gs17931:benchmarks :) > 
```

**Comment by ChrisTimperley** [comment]
Woops. Try dropping the -o option.

**Review by jlacomis — APPROVED** [review]
I'm fine with you merging this once the README is fixed. I'm not certain what `-o` even does, it doesn't seem to be documented.

**Comment by jlacomis** [comment]
Whoops, accidentally merged a lot of things instead of rebasing

**Comment by ChrisTimperley** [comment]
**Todo:** Add `--profile` as a flag to the benchmarking script.

**Pull request merged**
